package com.app.hibnate;
// Generated Apr 16, 2016 3:28:26 PM by Hibernate Tools 4.3.1.Final

import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.web.multipart.MultipartFile;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "mywyc")
public class Admin implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AdminId", unique = true, nullable = false)
	private Integer adminId;
	
	@Column(name = "AdminName", length = 45)
	private String adminName;
	
	@Column(name = "AdminPassword")
	private Integer adminPassword;
	
	@Column(name = "AdminPhone", length = 45)
	private String adminPhone;
	
	@Column(name = "AdminEmail", length = 45)
	private String adminEmail;
	
	@Column(name = "AdminImageName")
	private String adminImageName;
	
	@Column(name = "AdminImageFiletye")
	private String adminImageFiletye;
	
	@Transient
	private MultipartFile photo;
	
	@Column(name = "AdminData")
	@Lob private byte[] adminData;
	
	@Column(name = "authority")
	private String authority = "admin";
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	private Set<Recom> recommendations = new HashSet<Recom>(0);

	public Admin() {
	}

	public Admin(String adminName, Integer adminPassword, String adminPhone, String adminEmail, String adminImageName,
			String adminImageFiletye, byte[] adminData, String authority, Set<Recom> recommendations) {
		this.adminName = adminName;
		this.adminPassword = adminPassword;
		this.adminPhone = adminPhone;
		this.adminEmail = adminEmail;
		this.adminImageName = adminImageName;
		this.adminImageFiletye = adminImageFiletye;
		this.adminData = adminData;
		this.recommendations = recommendations;
		this.authority = "admin";
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public Integer getAdminPassword() {
		return this.adminPassword;
	}

	public void setAdminPassword(Integer adminPassword) {
		this.adminPassword = adminPassword;
	}

	public String getAdminPhone() {
		return this.adminPhone;
	}

	public void setAdminPhone(String adminPhone) {
		this.adminPhone = adminPhone;
	}

	public String getAdminEmail() {
		return this.adminEmail;
	}

	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}

	public String getAdminImageName() {
		return this.adminImageName;
	}

	public void setAdminImageName(String adminImageName) {
		this.adminImageName = adminImageName;
	}

	public String getAdminImageFiletye() {
		return this.adminImageFiletye;
	}

	public void setAdminImageFiletye(String adminImageFiletye) {
		this.adminImageFiletye = adminImageFiletye;
	}

	public byte[] getAdminData() {
		return this.adminData;
	}

	public void setAdminData(byte[] adminData) {
		this.adminData = adminData;
	}

	public Set<Recom> getRecommendations() {
		return this.recommendations;
	}

	public void setRecommendations(Set<Recom> recommendations) {
		this.recommendations = recommendations;
	}

	public MultipartFile getPhoto() {
		return photo;
	}

	public void setPhoto(MultipartFile photo) {
		this.photo = photo;
		
		setAdminImageName(photo.getOriginalFilename());
		setAdminImageFiletye(photo.getContentType());
		try {
			setAdminData(photo.getBytes());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
