package com.app.hibnate;
// Generated Apr 16, 2016 3:28:26 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Recommendation generated by hbm2java
 */
@Entity
@Table(name = "recom", catalog = "mywyc")
public class Recom implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RecommondationId", unique = true, nullable = false)
	private Integer recommondationId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AdminId")
	private Admin admin;
	
	@Column(name = "RecommondationDate", length = 50)
	private String recommondationDate;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recommendation")
	private Set<Item> items = new HashSet<Item>(0);

	public Recom() {
	}

	public Recom(Admin admin, String recommondationDate, Set<Item> items) {
		this.admin = admin;
		this.recommondationDate = recommondationDate;
		this.items = items;
	}

	public Integer getRecommondationId() {
		return this.recommondationId;
	}

	public void setRecommondationId(Integer recommondationId) {
		this.recommondationId = recommondationId;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getRecommondationDate() {
		return this.recommondationDate;
	}

	public void setRecommondationDate(String recommondationDate) {
		this.recommondationDate = recommondationDate;
	}

	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
