package com.app.hibnate;
// Generated Apr 19, 2016 3:57:52 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.io.IOException;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.web.multipart.MultipartFile;

/**
 * Step generated by hbm2java
 */
@Entity
@Table(name = "step", catalog = "mywyc")
public class Step implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "StepId", unique = true, nullable = false)
	private Integer stepId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ItemId", nullable = false)
	private Item item;
	
	@Column(name = "StepNumber")
	private Integer stepNumber;
	
	@NotEmpty
	@Column(name = "StepText")
	private String stepText;
	
	@Transient
	private MultipartFile image;
	
	@Column(name = "StepImageName")
	private String stepImageName;
	
	@Column(name = "StepImageFiletye")
	private String stepImageFiletye;
	
	@Column(name = "StepData")
	@Lob private byte[] stepData;

	public Step() {
	}

	public Step(Item item) {
		this.item = item;
	}

	public Step(Item item, Integer stepNumber, String stepText, String stepImageName, String stepImageFiletye,
			byte[] stepData) {
		this.item = item;
		this.stepNumber = stepNumber;
		this.stepText = stepText;
		this.stepImageName = stepImageName;
		this.stepImageFiletye = stepImageFiletye;
		this.stepData = stepData;
	}

	public Integer getStepId() {
		return this.stepId;
	}

	public void setStepId(Integer stepId) {
		this.stepId = stepId;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Integer getStepNumber() {
		return this.stepNumber;
	}

	public void setStepNumber(Integer stepNumber) {
		this.stepNumber = stepNumber;
	}

	public String getStepText() {
		return this.stepText;
	}

	public void setStepText(String stepText) {
		this.stepText = stepText;
	}

	public String getStepImageName() {
		return this.stepImageName;
	}

	public void setStepImageName(String stepImageName) {
		this.stepImageName = stepImageName;
	}

	public String getStepImageFiletye() {
		return this.stepImageFiletye;
	}

	public void setStepImageFiletye(String stepImageFiletye) {
		this.stepImageFiletye = stepImageFiletye;
	}

	public byte[] getStepData() {
		return this.stepData;
	}

	public void setStepData(byte[] stepData) {
		this.stepData = stepData;
	}

	public MultipartFile getImage() {
		return image;
	}

	public void setImage(MultipartFile image) {
		this.image = image;
		
		setStepImageName(image.getOriginalFilename());
		setStepImageFiletye(image.getContentType());
		try {
			setStepData(image.getBytes());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
}
